version: '3'
services:
  backend:
    build:
      context: ./StudentsRetake
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./student_retake
      dockerfile: Dockerfile
    ports:
      - 3000:3000